# bikes_checkUsersOptions
#===============================================================================
macro(CMakeBikes_init)
	get_curent_dir_name(THIS_DIR)
	
	set(DEF_FOR_STATIC_EXPORT)
	set(DEF_FOR_SHARED_EXPORT)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY NO)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY NO)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY NO)
	set(CMAKE_INSTALL_PREFIX NO)
	set(TARGET_NAME)
	set(HINT_PUBLIC_INCLUDE_PREFIX)

	set(PROJECT_TYPE) # AUTO|EXECUTABLE|SHARED_LIB|STATIC_LIB|SHARED_OR_STATIC_LIB|HEADERS_LIB|AGGREGATION
	set(REQUIRED_LIBS) # NO|[AUTO][DEPENDENCIES][PARENT_DEPENDENCIES][<REQUIRED_LIBS_LIST>]
	set(REQUIRED_INCLUDE) # NO|[<REQUIRED_TARGETS_LIST>]
	set(ADDITIONAL_INCLUDE_DIRS) # NO|<INCLUDE_DIRS_LIST>
	set(PRIVATE_DEFINITIONS) # NO|<DEFINITIONS_LIST>
	set(USERS_INCLUDE) # NO|[AUTO][PUBLIC][PRIVATE][DEPENDENCIES][ADDITIONAL][<INCLUDE_TARGETS_LIST>][<INCLUDE_DIRS_LIST>]
	set(USERS_DEFINITIONS) # NO|[AUTO][STATIC_EXPORT][SHARED_EXPORT][PRIVATE][<DEFINITIONS_LIST>]
	set(USE_PRECOMPILED_HEADER) # NO|AUTO|<HEADER_PATH>
	set(USE_BOOST) # ON|OFF
	set(USE_QT) # ON|OFF|[ON][AUTOMOC][CORE][MAIN][GUI][OPENGL][SVG][XML][SQL][NETWORK][3SUPPORT][WEBKIT][HELP][TEST]
	set(USE_INSTALL) # ON|OFF|<INSTALL_PATH>
endmacro()
#===============================================================================
macro(check_users_options)

	if(DEFINED PROJECT_TYPE)
		list(GET PROJECT_TYPE 0 v)
		set(PROJECT_TYPE ${v})
		if(PROJECT_TYPE)
			set(PROJECT_TYPE_CHECK  AUTO EXECUTABLE SHARED_LIB STATIC_LIB SHARED_OR_STATIC_LIB HEADERS_LIB AGGREGATION)
			list(FIND PROJECT_TYPE_CHECK ${PROJECT_TYPE} f)
			if(${f} EQUAL -1)
				set(PROJECT_TYPE AUTO)
			endif()
		else()
			set(PROJECT_TYPE AUTO)
		endif()
	else()
		set(PROJECT_TYPE AUTO)
	endif()

	ifnodef_set(REQUIRED_LIBS AUTO)
	ifnodef_set(REQUIRED_INCLUDE NO)
	ifnodef_set(ADDITIONAL_INCLUDE_DIRS NO)
	ifnodef_set(PRIVATE_DEFINITIONS NO)
	ifnodef_set(USERS_INCLUDE AUTO)
	ifnodef_set(USERS_DEFINITIONS AUTO)
	ifnodef_set(USE_PRECOMPILED_HEADER AUTO)
	ifnodef_set(USE_BOOST OFF)
	ifnodef_set(USE_QT OFF)
	ifnodef_set(USE_INSTALL .)


	ifndef_set(OUT_ROOT_DIR			${CMAKE_BINARY_DIR})
	ifndef_set(OUT_LIB_DIR			lib)
	ifndef_set(OUT_BIN_DIR			bin)
	ifndef_set(OUT_INSTALL_DIR		dist)
	ifndef_set(HINT_SOURCES_DIR			src sources)  
	ifndef_set(HINT_INCLUDE_DIR			include headers) 
	ifnodef_set(HINT_PUBLIC_INCLUDE_PREFIX	${PROJECT_NAME}) #!
	ifndef_set(HINT_DEPENDENCIES_DIR		dependencies libraries libs) 
	ifndef_set(HINT_SAMPLES_DIR			sample* demo* test* tools) 
	ifndef_set(HINT_RESOURCES_DIR			resource*)
	ifndef_set(HINT_IGNOR_DIRS				.git build CMakeModules CMakeBikes doc 
									${OUT_LIB_DIR} ${OUT_BIN_DIR} 
									${OUT_INSTALL_DIR} ${CMAKE_BINARY_DIR}) # NO REGEXP! 
	# <- Каталоги

	# Файлы ->
	ifndef_set(HINT_PRECOMPILED_HEADER	precompil* prerequisit* )
	ifndef_set(HINT_EXPORT_HEADER		export* )
	ifndef_set(HINT_MAIN_SOURCE		main )
	# <- Файлы

	# Расширения файлов ->
	ifndef_set(HINT_EXT_HEADERS		h hpp )
	ifndef_set(HINT_EXT_SOURCES		cpp cc c )
	ifndef_set(HINT_EXT_QT_RESOURCES	qrc )
	ifndef_set(HINT_EXT_QT_UI			ui )
	ifndef_set(OUT_EXT_MOC				cxx)
	# <- Расширения файлов 

	# Определения препроцесcора ->
	if(NOT DEFINED DEF_FOR_STATIC_EXPORT)
		set(DEF_FOR_STATIC_EXPORT	${PROJECT_NAME}_STATICLIB )
		string(TOUPPER ${DEF_FOR_STATIC_EXPORT} DEF_FOR_STATIC_EXPORT)
	endif()
	if(NOT DEFINED DEF_FOR_SHARED_EXPORT)
		set(DEF_FOR_SHARED_EXPORT	${PROJECT_NAME}_SHAREDLIB )
		string(TOUPPER ${DEF_FOR_SHARED_EXPORT} DEF_FOR_SHARED_EXPORT)
	endif()
	# <- Определения препроцесcора 

	# Цель ->
	ifnodef_set(TARGET_NAME ${PROJECT_NAME})
	# <- Цель
	
	ifndef_set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUT_ROOT_DIR}/${OUT_LIB_DIR})
	ifndef_set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUT_ROOT_DIR}/${OUT_LIB_DIR})
	ifndef_set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUT_ROOT_DIR}/${OUT_BIN_DIR})
	ifndef_set(CMAKE_INSTALL_PREFIX ${OUT_ROOT_DIR}/${OUT_INSTALL_DIR})

	message_var(CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
	message_var(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
	message_var(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
	message_var(CMAKE_INSTALL_PREFIX)
	
	message_var(PROJECT_TYPE) # AUTO|EXECUTABLE|SHARED_LIB|STATIC_LIB|SHARED_OR_STATIC_LIB|HEADERS_LIB|AGGREGATION
	message_var(REQUIRED_LIBS) # NO|[AUTO][DEPENDENCIES][PARENT_DEPENDENCIES][<REQUIRED_LIBS_LIST>]
	message_var(REQUIRED_INCLUDE) # NO|[<REQUIRED_TARGETS_LIST>]
	message_var(ADDITIONAL_INCLUDE_DIRS) # NO|<INCLUDE_DIRS_LIST>
	message_var(PRIVATE_DEFINITIONS) # NO|<DEFINITIONS_LIST>
	message_var(USERS_INCLUDE) # NO|[AUTO][PUBLIC][PRIVATE][DEPENDENCIES][ADDITIONAL][<INCLUDE_TARGETS_LIST>][<INCLUDE_DIRS_LIST>]
	message_var(USERS_DEFINITIONS) # NO|[AUTO][STATIC_EXPORT][SHARED_EXPORT][PRIVATE][<DEFINITIONS_LIST>]
	message_var(USE_PRECOMPILED_HEADER) # NO|AUTO|<HEADER_PATH>
	message_var(USE_BOOST) # ON|OFF
	message_var(USE_QT) # ON|OFF|[ON][AUTOMOC][CORE][MAIN][GUI][OPENGL][SVG][XML][SQL][NETWORK][3SUPPORT][WEBKIT][HELP][TEST]
	message_var(USE_INSTALL) # ON|OFF|<INSTALL_PATH>
endmacro()
#===============================================================================

