message(STATUS "\nInclude CMakeBikes.")
include(bikes_checkUsersOptions)
include(bikes_messageFuncs)
include(bikes_stringFuncs)
include(bikes_fileFuncs)
include(bikes_readAlien)
include(bikes_aux)
include(bikes_CMakeListsBody)
include(bikes_useQt)